---
# tasks file for ansible-avahi
- name: Alpine related tasks
  ansible.builtin.include_tasks: alpine.yml
  when: ansible_os_family == "Alpine"

- name: Debian related tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: RHEL related tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Configure Avahi
  ansible.builtin.include_tasks: config.yml
  when: avahi_config
